### ISSUE TITLE
Enable https protocol for git calls

### ISSUE THREAD

**Issue by frhd** [sapegin/bower-update#12]
I would like to use `https://` instead of `git://` for git calls.

Hower, `git config --global url."https://".insteadOf git://` doesn't seem to affect `bower-update` so I get things like that (due to firewall policies, I guess):

```
Error: Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-i18n.git", exit code of #128
```

Any clues?

**Comment by sapegin** [comment]
It’s not related to bower-update, it’s Bower issue. 

http://stackoverflow.com/questions/15669091/bower-install-using-only-https/15684898#15684898

**Comment by frhd** [comment]
Strange, I have no issues with bower at all. Only `bower-update` does not work and gives me the error mentioned above.

**Comment by sapegin** [comment]
Maybe, they are under an attack right now. Let’s wait some time.
