### ISSUE TITLE
Bower now officially supported in npm-check-updates

### ISSUE THREAD

**Issue by metaraine** [sapegin/bower-update#19]
Hi! Thanks for creating this package. I wanted to let you know that [npm-check-updates](https://github.com/tjunnone/npm-check-updates) now supports bower. Would you be open to putting a link in the README? It would be a nice reference for those who need some of the advanced options that are not available in this package.

Let me know and I can submit a pull request to edit the README.

**Comment by sapegin** [comment]
Great news! I’ll be happy to deprecate this project in favor of ncu. I use ncu myself for Node. Feel free to send me a PR ;-)

P. S. The only thing is missing in ncu (that exists in bower-update) is the interactive mode.

**Comment by metaraine** [comment]
Great, thanks!

Interactive mode is on the roadmap for npm-check-updates, just hasn't been a priority. I think it would be a good addition though.

Closing this issue to open a pull request for the README changes.
